In [1]:
import nglview as nv
import mdtraj as md
import numpy as np
import os
import glob
import argparse
import pickle
import ipywidgets as widgets
import pytraj as pt


benchmarkFolder = '../sims/000113_all_12368_cyrusc_081724'
#benchmarkFolder = '../sims/000112*'
# get list of proteins
npyFiles = glob.glob(f'{benchmarkFolder}/*_model_replicas.npy')
print('npyFiles',npyFiles)
# for file in npyFiles:
file = npyFiles[0]
with open(file, 'rb') as f:
    struct = pickle.load(f)
    trajs = struct['mdtraj_list']

t = trajs[0]
box_lengths = t.unitcell_lengths  # Shape: (n_frames, 3)
box_angles = t.unitcell_angles    # Shape: (n_frames, 3)



npyFiles ['../sims/000113_all_12368_cyrusc_081724/wwdomain_model_replicas.npy', '../sims/000113_all_12368_cyrusc_081724/proteinb_model_replicas.npy', '../sims/000113_all_12368_cyrusc_081724/trpcage_model_replicas.npy', '../sims/000113_all_12368_cyrusc_081724/chignolin_model_replicas.npy', '../sims/000113_all_12368_cyrusc_081724/bba_model_replicas.npy', '../sims/000113_all_12368_cyrusc_081724/homeodomain_model_replicas.npy']


In [2]:
# print(t.xyz)
# print('box_lengths',box_lengths)
# print('box_angles', box_angles)
# asd
rows = 1
cols = 2
c = 0
grid = widgets.GridspecLayout(rows, cols)  # Create a 1-row, 2-column grid        
for r in range(0, rows):
    for c in range(0, cols):
        # t_processed = pt.autoimage(trajs[c])  # Apply periodic boundary corrections
        # t_processed = pt.superpose(t_processed, ref=0)  # Superpose frames on the first frame for consistency

        # Create NGLWidget instances
        view = nv.show_pytraj(trajs[c])
        view.center()  # Center the view
        view.add_representation('box', color='blue')  # Add bounding box
        # view.add_unitcell()
        view.camera = 'orthographic'  # Use orthographic view for consistency
        view.frame = 1  # Move to the second frame (frame indices are zero-based)
        grid[r, c] = view
        view.display(gui=True)
        
        c += 1

grid

ThemeManager()

GridspecLayout(children=(NGLWidget(frame=1, gui_style='ngl', layout=Layout(grid_area='widget001'), max_frame=9…

In [44]:
# merge all mdtraj trajectories into one system, translate each mdtraj by xyz offsets, and display them in nglview
import copy

ts_shifted = [copy.deepcopy(t) for t in trajs[:5]]
# xyzs = np.linspace(0, 100, len(ts_shifted))
for t, tj in enumerate(ts_shifted):
    tj.xyz += np.array([t, 0, 0])  # Randomly shift each trajectory
    print('tj.xyz', tj.xyz[0,:,:])

merged = md.join(ts_shifted)
print('merged',merged)
# Create NGLWidget instance
view = nv.show_mdtraj(merged)
view.center()  # Center the view
view.display(gui=True)
view


tj.xyz [[-1.3318918  -1.7194725   4.128478  ]
 [-1.0169213  -1.6046295   4.3000216 ]
 [-0.79844403 -1.7894714   4.554266  ]
 ...
 [ 1.1404959   1.0054432   4.7851386 ]
 [ 1.0617161   0.99277246  5.1574764 ]
 [ 1.2581224   1.2917459   4.979723  ]]
tj.xyz [[ 6.1822677  -0.5836967   3.967289  ]
 [ 6.423429   -0.3068933   3.8718047 ]
 [ 6.6934495  -0.08159108  4.05932   ]
 ...
 [ 4.661863    0.11590022  5.380454  ]
 [ 4.2974753   0.01744992  5.317434  ]
 [ 4.5225086   0.30028448  5.183049  ]]
tj.xyz [[1.7679139 5.1220546 3.196375 ]
 [1.6537393 4.9833136 2.8449214]
 [1.9858665 4.787259  2.7921128]
 ...
 [1.220552  3.6711159 3.6838355]
 [1.4763793 3.7897925 3.4202805]
 [1.4075588 4.054866  3.6976047]]
tj.xyz [[ 8.709774   -0.4418696   0.41975102]
 [ 8.477692   -0.7216612   0.54654795]
 [ 8.247654   -0.795837    0.23738284]
 ...
 [ 7.41857     0.9637488  -0.4117295 ]
 [ 7.5073876   0.65711915 -0.62909436]
 [ 7.7602363   0.9079194  -0.7854816 ]]
tj.xyz [[ 7.800406   -0.4986356   3.1267412 ]
 [

NGLWidget(gui_style='ngl', max_frame=499)